ReservaHospedagemApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('anfitriao/', include('anfitriao.urls', namespace='anfitrioes')),
    path('hospede/', include('hospede.urls', namespace='hospedes')),
    path('contas/', include('accounts.urls', namespace='accounts')),
    path('imovel/', include('imovel.urls', namespace='imovel')),
    path('comodidade/', include('comodidade.urls', namespace='comodidade')),
    path('servico_adicional/', include('servico_adicional.urls', namespace='servico_adicional')),
    path('item_reserva/', include('item_reserva.urls', namespace='item_reserva')),
    path('reserva/', include('reserva.urls', namespace= 'reserva')),
    path('comodidade_imovel/', include('comodidade_imovel.urls', namespace= 'comodidade_imovel')),
    path('avaliacao/', include('avaliacao.urls', namespace= 'avaliacao')),
    path('pagamento/', include('pagamento.urls', namespace= 'pagamento')),
    

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/hospede/urls.py
from django.urls import path
from . import views

app_name = 'hospedes'

urlpatterns = [
    path('adicionar/', views.add_hospedes, name='add_hospedes'),
    path('', views.list_hospedes, name='list_hospedes'),
    path('editar/<int:id_hospede>/', views.edit_hospedes, name='edit_hospedes'),
    path('excluir/<int:id_hospede>/', views.delete_hospedes, name='delete_hospedes'),
]

apps/hospede/models.py
from django.db import models

class Hospede(models.Model):
    name = models.CharField('Nome', max_length=50)
    email = models.EmailField('Email', max_length=100)
    password = models.CharField ('Senha', max_length=50)
    telephone = models.CharField('Telefone', max_length=13)
    
    
    class Meta:
        verbose_name = 'Hospede'
        verbose_name_plural = 'Hospedes'
        ordering =['id']

    def __str__(self):
        return self.name

apps/hospede/forms.py
from django import forms
from .models import Hospede

class HospedeForm(forms.ModelForm):

    class Meta:
        model = Hospede
        exclude = ()

apps/hospede/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import HospedeForm
from .models import Hospede

def add_hospedes(request):
    template_name = 'hospedes/add_hospedes.html'
    context = {}
    if request.method == 'POST':
        form = HospedeForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            form.save_m2m()
            return redirect('/hospede')
    form = HospedeForm()
    context['form'] = form
    return render(request, template_name, context)


def list_hospedes(request):
    template_name = 'hospedes/list_hospedes.html'
    hospedes = Hospede.objects.filter()
    context = {
        'hospedes': hospedes
    }
    return render(request, template_name, context)

def edit_hospedes(request, id_hospede):
    template_name = 'hospedes/add_hospedes.html'
    context ={}
    hospede = get_object_or_404(Hospede, id=id_hospede)
    if request.method == 'POST':
        form = HospedeForm(request.POST, instance=hospede)
        if form.is_valid():
            form.save()
            return redirect('hospedes:list_hospedes')
    form = HospedeForm(instance=hospede)
    context['form'] = form
    return render(request, template_name, context)



def delete_hospedes(request, id_hospede):
    hospede = Hospede.objects.get(id=id_hospede)
    hospede.delete()
    return redirect('hospedes:list_hospedes')

templates/hospedes/add_hospedes.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Hospedes - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Cadastro de Hospedes</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">
                   <label for="{{ form.name.id_for_label }}">Nome</label>
                   {{ form.name|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.email.id_for_label }}">Email</label>
                    {{ form.email|add_class:"form-control" }}
                 </div>
                 <div class="form-group">
                    <label for="{{ form.password.id_for_label }}">Senha</label>
                    {{ form.password|add_class:"form-control" }}
                 </div>
                 <div class="form-group">
                    <label for="{{ form.telephone.id_for_label }}">Telefone</label>
                    {{ form.telephone|add_class:"form-control" }}
                 </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

templates/hospedes/list_hospedes.html
{% extends 'base.html' %}

{% block title %}

    Lista de Hospedes - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Lista de Hospedes</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <br />
                    <a href="{% url 'hospedes:add_hospedes' %}">Cadastro de Hospedes</a>
                <br />
                <br />
                <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Email</th>
                    <th scope="col">Senha</th>
                    <th scope="col">Telefone</th>
                    <th scope="col">Editar</th>
                    <th scope="col">Excluir</th>
                    </tr>
                </thead>
                <tbody>
                    {% for hospede in hospedes %}
                        <tr>
                            <th scope="row">{{ hospede.id }}</th>
                            <td>{{ hospede.name }}</td>
                            <td>{{ hospede.email }}</td>
                            <td>{{ hospede.password }}</td>
                            <td>{{ hospede.telephone }}</td>
                            <td>
                                <a href="{% url 'hospedes:edit_hospedes' hospede.id %}" class="btn btn-primary btn-sm">Editar</a>
                            </td>
                            <td>
                                <a href="{% url 'hospedes:delete_hospedes' hospede.id %}" class="btn btn-danger btn-sm ">Excluir</a>
                            </td>
                        </tr> 
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock body %}